<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP-5CG1482VRX" failures="7" tests="34" name="pageTest.AddArtistPageTest" time="813.046" errors="0" timestamp="2025-07-07T00:50:14 IST" skipped="14">
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="9.032">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.679">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.109">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pageTest.AddArtistPageTest.TC01_verify_PhoneNumber_Field_validation(AddArtistPageTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.476"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.058">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pageTest.AddArtistPageTest.TC01_verify_PhoneNumber_Field_validation(AddArtistPageTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="9.517">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at pageTest.AddArtistPageTest.TC01_verify_PhoneNumber_Field_validation(AddArtistPageTest.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.671">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.069">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pageTest.AddArtistPageTest.TC01_verify_PhoneNumber_Field_validation(AddArtistPageTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC03_verify_EmailPattren_Field_Validation" time="24.397">
    <skipped/>
  </testcase> <!-- TC03_verify_EmailPattren_Field_Validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page" time="30.712">
    <skipped/>
  </testcase> <!-- TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC03_verify_EmailPattren_Field_Validation" time="25.438">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pageTest.AddArtistPageTest.TC03_verify_EmailPattren_Field_Validation(AddArtistPageTest.java:179)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC03_verify_EmailPattren_Field_Validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.747">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC02_Required_Field_Validation" time="24.905"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.222">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC03_verify_EmailPattren_Field_Validation" time="24.461">
    <skipped/>
  </testcase> <!-- TC03_verify_EmailPattren_Field_Validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC02_Required_Field_Validation" time="24.921"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC02_Required_Field_Validation" time="24.945"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page" time="31.538">
    <skipped/>
  </testcase> <!-- TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.604">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.638"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC05_Verify_New_artist_can_be_added_in_add_artist_page" time="30.150"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page" time="30.840">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at pageTest.AddArtistPageTest.TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page(AddArtistPageTest.java:333)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC004_Verify_Newly_added_Artist_details_are_displayed_in_About_artist_page -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC02_Required_Field_Validation" time="25.036"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC02_Required_Field_Validation" time="24.635"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.807"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC03_verify_EmailPattren_Field_Validation" time="24.985"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.373">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.590">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pageTest.AddArtistPageTest.TC01_verify_PhoneNumber_Field_validation(AddArtistPageTest.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="24.641">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.338"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="25.132">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC04_Verify_the_entered_data_should_be_removed_from_the_fields_when_user_click_on_the_reset_form_CTA_in_Add_Artist_page" time="15.045"/>
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC01_verify_PhoneNumber_Field_validation" time="9.971">
    <skipped/>
  </testcase> <!-- TC01_verify_PhoneNumber_Field_validation -->
  <system-out/>
  <testcase classname="pageTest.AddArtistPageTest" name="TC03_verify_EmailPattren_Field_Validation" time="24.364"/>
  <system-out/>
</testsuite> <!-- pageTest.AddArtistPageTest -->
